### ISSUE TITLE
Post Story Page

### ISSUE THREAD

**Issue by kkennethlee** [kkennethlee/c7_blog_project#4]
This is a place where a user types in stories. For example: Text Box

**Comment by nbidler** [comment]
Going to make basic features of page - text box for story, display box for selected prompt, and placeholder for basic navigation (to where is not known at this point)

**Comment by nbidler** [comment]
skeleton ready, needs to be approved to merge with version branch - working on getting page ready for angular/dynamic elements/server interaction
