### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by kkennethlee** [kkennethlee/c7_blog_project#6]
Assigned to Tim and Kenneth

-Structure the MySQL data table
-Username, Prompt, Stories, etc.

**Comment by TimelikeClosure** [comment]
Current tables for first phase of functionality:

- users - All users, user information, and permissions
- storys - All stories, base story information, and owning users
- prompts - All prompts, base prompt info, and owning users
- story_prompts - Prompts included in each story, response

**Comment by TimelikeClosure** [comment]
Current structure for `users` table:

- `ID` - User's primary ID number. Used on other tables to keep track of ownership. (autofilled on creation)
- `username` - User's public username
- `email` - User's email address
- `created` - timestamp user was created (autofilled on creation)
- `active` - whether user is active (autofilled on creation)

**Comment by TimelikeClosure** [comment]
Current structure for `storys` table:

- `ID` - Story's primary ID number.
- `title` - Story's title
- `summary` - Story's summary
- `user_id` - creator's user id number

**Comment by TimelikeClosure** [comment]
Current structure for `prompts` table:

- `ID` - Prompt's primary ID number.
- `description` - Prompt's full text
- `category` - Which element of a story the prompt applies to. Currently just a description.
- `genre` - Which genre the prompt applies to: Currently just a description.
- `setting` - Which setting the prompt applies to: Currently just a description.
- `user_id` - creator's user id number

**Comment by TimelikeClosure** [comment]
Current structure for `story_prompts` table:

- `ID` - Story-prompt match ID number
- `story_id` - Story ID number
- `prompt_id` - Prompt ID number
- `response` - User's response to prompt

**Comment by TimelikeClosure** [comment]
Update database schema to include user password and story full_text fields.

**Comment by TimelikeClosure** [comment]
This project is no longer supported.
