### ISSUE TITLE
Write Prompt saves title input text after you have already submitted

### ISSUE THREAD

**Issue by trishameyer** [kkennethlee/c7_blog_project#85]
The title input doesn't clear after you submit the prompt
![screen shot 2016-03-25 at 10 53 32 am](https://cloud.githubusercontent.com/assets/16482002/14050321/4d30a940-f278-11e5-829c-ba107b2ad2ca.png)

**Comment by PaulLy28** [comment]
fixed issue# 85 for the title not clearing once submitted.
